export enum PersonCategory {
  STAFF = 'Staff',
  STUDENT = 'Student',
  PARENT = 'Parent/Guardian',
}

export interface Person {
  id: number;
  category: PersonCategory;
  firstName: string;
  lastName: string;
  image: string; // Base64 encoded image or URL
  role?: string; // For Staff
  class?: string; // For Students
  guardianIds?: number[]; // For Students
  bio: string; // Generated by Gemini
  googleSheetId: string; // Simulated lookup
}

export interface Settings {
  [key: string]: string;
}

// A lightweight type for populating guardian/staff names
export interface Associate {
  id: number;
  firstName: string;
  lastName: string;
}
